### ISSUE TITLE
Implement search filter with empty value

### ISSUE THREAD

**Issue by programgames** [php-etl/akeneo-plugin#11]
In this case : 
```
      - akeneo:
          enterprise: false
          extractor:
            type: product
            method: all
            search:
              - { field: parent, operator: 'EMPTY' }
```
The pipeline should be built without using the value field as some operator like 'EMPTY' does not accept any value :
https://api.akeneo.com/documentation/filter.html#on-their-parent-2
